pipeline {
    agent any 
      tools {
        jdk 'LocalJDK'
        maven 'LocalMaven'
    }
    stages {
        stage('clone repo and clean it') { 
            steps {
                 dir('Hello_SpringBoot') {
                     bat "mvn clean"
                 }
            }
        }
        stage('Test') { 
            steps {
                dir('Hello_SpringBoot') {
                    bat "mvn test"
                }
            }
        }
        stage('Deploy') { 
            steps {
                dir('Hello_SpringBoot') {
                    bat "mvn package" 
                }
            }
        }
    }
}
